project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "infieri"
  favicon: logo.svg
  navbar:
    pinned: true
    logo: logo.svg
    logo-alt: "infieri"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/semper-infieri
        aria-label: GitHub
        target: _blank
      - icon: bluesky
        href: https://bsky.app/profile/semper-infieri.bsky.social
        aria-label: Bluesky
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/yana-gorobets-366687441/
        aria-label: LinkedIn
        target: _blank
      - icon: envelope-at-fill
        href: mailto:semper.infieri@gmail.com
        aria-label: Email
format:
  html:
    theme: [cosmo, custom.scss]
    css: styles.css
    anchor-sections: false
    include-after-body: partials/menu-close.html



